name = "HarmonieNamelist"
uuid = "fca5d4e6-e5c9-45f7-9e2d-c2c123526d62"
authors = ["roel <Roel.stappers@gmail.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
